# Generated by Django 5.2.6 on 2026-03-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
