# Generated by Django 5.2.6 on 2026-03-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunan_app', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('first_line_address', models.CharField(max_length=255)),
                ('second_line_address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('license_no', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_person', models.CharField(max_length=255)),
                ('emergency_contact_no', models.CharField(max_length=255)),
                ('medical_history', models.CharField(max_length=255)),
                ('current_medication', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.counselor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.counselor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_medicine', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.counselor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunan_app.patient')),
            ],
        ),
    ]
